services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_SERVICE_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: adminer_ui
    ports:
      - "${ADMINER_SERVICE_PORT:-9000}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db